### ISSUE TITLE
Incorrect  calculating of remaining space in backpack

### ISSUE THREAD

**Issue by lsereda** [hjaremko/io-rpg#115]
At the beginning of the game, when you equip sword you have more space in backpack than after throwing sword.

How to reproduce?
0. Start game
1. equip Sword
2. backpack (now you can see, that remaining space 16)
3. off Sword
4. throw Sword
5. backpack (now you can see that remaining space equals 13)

**Comment by hjaremko** [comment]
This is a feature. The assumption is that if your attack is higher you are also stronger and can carry more. Base capacity is 10 and every attack point add 3 more. Base attack is 1 so overall base capacity is 13.
